# Generated by Django 4.1.4 on 2022-12-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('verification', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(blank=True, max_length=900, null=True)),
                ('option1', models.CharField(blank=True, max_length=900, null=True)),
                ('option2', models.CharField(blank=True, max_length=900, null=True)),
                ('option3', models.CharField(blank=True, max_length=900, null=True)),
                ('option4', models.CharField(blank=True, max_length=900, null=True)),
                ('answer', models.CharField(blank=True, max_length=900, null=True)),
                ('current_affairs', models.BooleanField(blank=True, default=False, null=True)),
                ('current_affairs_date', models.CharField(blank=True, max_length=900, null=True)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.chapter')),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
                ('subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
    ]
