# Generated by Django 4.0.6 on 2022-08-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
