# Generated by Django 4.0.6 on 2022-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_junoosubcategory'),
        ('questions', '0003_questions_option3_questions_option4'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='junoocategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory'),
        ),
        migrations.AddField(
            model_name='subject',
            name='junoosubcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory'),
        ),
    ]
