# Generated by Django 4.1.4 on 2022-12-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quize_attended_questions',
            name='quize',
        ),
        migrations.RemoveField(
            model_name='quize_attended_questions',
            name='quizehistory',
        ),
        migrations.AddField(
            model_name='quize_attended_questions',
            name='ExamList',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.examlist'),
        ),
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attended_code', models.CharField(blank=True, max_length=200, null=True)),
                ('total_questions', models.CharField(blank=True, max_length=200, null=True)),
                ('total_right_answers', models.CharField(blank=True, max_length=200, null=True)),
                ('total_wrong_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('total_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('ExamList', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.examlist')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appapi.customer')),
            ],
        ),
        migrations.AddField(
            model_name='quize_attended_questions',
            name='ExamHistory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appapi.examhistory'),
        ),
    ]
