# Generated by Django 4.1.4 on 2022-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_remove_quize_attended_questions_examhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_attended_questions',
            old_name='quize_attended_code',
            new_name='exam_attended_code',
        ),
    ]
