# Generated by Django 4.1.4 on 2022-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_rename_quize_attended_code_exam_attended_questions_exam_attended_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize_attended_questions',
            name='selected_ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
