# Generated by Django 4.1.4 on 2022-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_quize_attended_questions_selected_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_attended_questions',
            name='selected_ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
