# Generated by Django 4.1.4 on 2022-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_exam_attended_questions_selected_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blockedReason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='isBlocked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
