# Generated by Django 4.1.4 on 2022-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_customer_blockedreason_customer_isblocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_totalpoint',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=8, null=True),
        ),
    ]
