# Generated by Django 4.1.4 on 2022-12-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('quizes', '0004_specialexam_publishtime'),
        ('appapi', '0009_alter_customer_current_totalpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attended_code', models.CharField(blank=True, max_length=200, null=True)),
                ('total_questions', models.CharField(blank=True, max_length=200, null=True)),
                ('total_right_answers', models.CharField(blank=True, max_length=200, null=True)),
                ('total_wrong_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('total_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('attended_time', models.CharField(blank=True, max_length=200, null=True)),
                ('iscutoffpassed', models.BooleanField(blank=True, default=False, null=True)),
                ('point_claimed', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appapi.customer')),
                ('specialExam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.specialexam')),
            ],
        ),
        migrations.CreateModel(
            name='SPExam_attended_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attended_code', models.CharField(blank=True, max_length=200, null=True)),
                ('right_wrong', models.BooleanField(blank=True, default=False, null=True)),
                ('crt_option', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_ans', models.CharField(blank=True, max_length=200, null=True)),
                ('SPExamHistory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appapi.spexamhistory')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appapi.customer')),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('specialExam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.specialexam')),
            ],
        ),
    ]
