# Generated by Django 4.1.4 on 2022-12-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0010_spexamhistory_spexam_attended_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizehistory',
            name='earnedpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizehistory',
            name='is_passed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
