# Generated by Django 4.1.4 on 2022-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0011_quizehistory_earnedpoint_quizehistory_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhistory',
            name='earnedpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='is_passed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
