# Generated by Django 4.1.4 on 2022-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0012_examhistory_earnedpoint_examhistory_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spexamhistory',
            name='earnedpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spexamhistory',
            name='is_passed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
