# Generated by Django 4.1.4 on 2022-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0013_spexamhistory_earnedpoint_spexamhistory_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='used_or_get',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
