# Generated by Django 4.1.4 on 2022-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0014_pointhistory_used_or_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhistory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizehistory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spexamhistory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
