# Generated by Django 4.1.4 on 2023-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0015_examhistory_created_date_quizehistory_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='customers'),
        ),
    ]
