# Generated by Django 4.1.4 on 2023-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0016_customer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhistory',
            name='created_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizehistory',
            name='created_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spexamhistory',
            name='created_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
