# Generated by Django 4.1.4 on 2023-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0017_examhistory_created_time_quizehistory_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examhistory',
            name='created_time',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizehistory',
            name='created_time',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spexamhistory',
            name='created_time',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
