# Generated by Django 4.1.4 on 2022-12-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('questions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_id', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_time', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_emojy', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_primary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_secondary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_details', models.CharField(blank=True, max_length=200, null=True)),
                ('quize_cutoffmark', models.CharField(blank=True, max_length=200, null=True)),
                ('win_price', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_fee', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='quize_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('quize', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.quize')),
            ],
        ),
        migrations.CreateModel(
            name='ExamsCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('el_id', models.CharField(blank=True, max_length=200, null=True)),
                ('el_time', models.CharField(blank=True, max_length=200, null=True)),
                ('el_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('el_emojy', models.CharField(blank=True, max_length=200, null=True)),
                ('el_primary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('el_secondary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('el_details', models.CharField(blank=True, max_length=200, null=True)),
                ('el_positivemark', models.CharField(blank=True, max_length=200, null=True)),
                ('negativemark', models.CharField(blank=True, max_length=200, null=True)),
                ('el_cutoffmark', models.CharField(blank=True, max_length=200, null=True)),
                ('win_price', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_fee', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('pre_or_moc', models.BooleanField(blank=True, default=False, null=True)),
                ('ExamCategorys', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.examscategorys')),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='exam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamList', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.examlist')),
                ('questions', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
