# Generated by Django 4.1.4 on 2022-12-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('masters', '0001_initial'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('el_id', models.CharField(blank=True, max_length=200, null=True)),
                ('el_time', models.CharField(blank=True, max_length=200, null=True)),
                ('el_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('el_emojy', models.CharField(blank=True, max_length=200, null=True)),
                ('el_primary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('el_secondary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('el_details', models.CharField(blank=True, max_length=200, null=True)),
                ('el_positivemark', models.CharField(blank=True, max_length=200, null=True)),
                ('negativemark', models.CharField(blank=True, max_length=200, null=True)),
                ('el_cutoffmark', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('result_published', models.BooleanField(blank=True, default=False, null=True)),
                ('opportunity_to_get_mark', models.CharField(blank=True, max_length=200, null=True)),
                ('win_price', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_fee', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('pre_or_moc', models.BooleanField(blank=True, default=False, null=True)),
                ('junoocategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoocategory')),
                ('junoosubcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.junoosubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='spexam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
                ('specialExam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.specialexam')),
            ],
        ),
    ]
