# Generated by Django 4.1.4 on 2022-12-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_specialexam_spexam_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialexam',
            name='pre_or_moc',
        ),
    ]
