# Generated by Django 4.1.4 on 2022-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_specialexam_pre_or_moc'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialexam',
            name='publishtime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
